<?php
return [
    'ADMIN' => '2',
    'SUPER_ADMIN' => '1',
    'ACTIVE' => '0',
    'UN_VERIFIED' => '1',
    'OUT' => '2',
    'PAID' => '1',
    'UN_PAID' => '0',
    'ATM' => '1',
    'COD' => '0',
    'PENDING' => '0',
    'PENDED' => '1',
    'SHIPPING' => '2',
    'SHIPPED' => '3',
    'CANCEL' => '4',
    'PHONE' => '1',
    'SPEAKER' => '2',
    'ACCESSORY' => '5',
];
